# -*- coding: utf-8 -*-
"""Spark2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DZva8u_7sjVWCf3a-bhAul-JaV9F4HZ

READING CSV FILE
"""

from pyspark.sql import *
spark = SparkSession.builder.appName('Pracrticing Spark').getOrCreate()
df = spark.read.csv(path = "/content/country_wise_latest.csv", header=True)
df.show(n = 100)
df.count()
df.explain()

df.select("Country/Region","Deaths").show(n = 50)

df.where(df['Deaths']>1000).show()

df = df.withColumn("Active",df['Active'].cast('int'))
df = df.withColumn("Deaths",df['Deaths'].cast('int'))
df.where((df['Active']>1000)&(df['Deaths']>1000)).orderBy('Active').show()